<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="description" content="Demonstrates some basic HTML content elements and CSS" />
  <meta name="keywords" content="HTML5, tags" />
  <meta name="author" content="A Lecturer"  />
  <title>HTML Structure and Content Elements + CSS</title>
  <link rel="stylesheet" href="lab04.css" />
</head>
<!-- This is a comment. Indenting child elements makes the markup much more readable -->
<body>
   <header>
     <h1>HTML 5 Structure and Content Elements with some CSS</h1>
     <nav>
         <a href="#headings">Heading and Paragraphs</a> 
         <a href="#sc">Special Characters</a> 
         <a href="#lists">Lists</a> 
         <a href="#tables">Tables</a>
         <a href="#images">Images</a>
         <a href="#hyperlinks">Hyperlinks</a>
      </nav>
      <hr />
   </header>